spring:
  datasource:
    url: jdbc:mysql://localhost:3306/altenHotel
    username: root
    password: root@1234
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    spring.jpa.hibernate.ddl-auto: validate
  flyway:
    enabled: true
    locations:
      - classpath:db/migration
